🎉 init : Set up initial newspeed-app project structure
play-hooky/newspeed-app pull request #8
Opened 2023-08-04 04:38 UTC by beolggoolosori

### expo 세팅 변경커밋 pr 입니다

```
/newspeed-app
├── .expo
├── assets
├── app
├── src
│   ├── components
│   │   ├── atoms
│   │   ├── molecules
│   │   ├── organisms
│   │   ├── templates
│   │   └── pages
│   └── constants
├── app.json
├── tsconfig.json
├── package-lock.json
└── package.json
```

2023-08-08 01:19 UTC, imzeze requested changes
확인 부탁드립니다..!

2023-08-08 01:19 UTC, imzeze commented on app/_layout.tsx
> +import { createStackNavigator } from '@react-navigation/stack';
이거 관련해서 참고하신 문서 url 부탁드립니다.

2023-08-08 01:19 UTC, imzeze commented on app/index.tsx
> +import {View,Text} from 'react-native';
eslint, prettier 설정 부탁드립니다.

2023-08-08 01:19 UTC, imzeze commented on assets/images/sign_apple_large.png
image 파일 figma에서 export 하는 방법 알려드릴게요
이하 이미지 역시 동일합니다. 추후 수정 부탁드려요

2023-08-08 01:19 UTC, imzeze commented on expo-env.d.ts
내용이 없기 때문에 우선 삭제 바랍니다.!

2023-08-08 01:19 UTC, imzeze commented on metro.config.js
현재 필요한 설정이 없기 때문에 우선 삭제 바랍니다.!

2023-08-08 01:19 UTC, imzeze commented on package.json
> +  "name": "my-app",
newspeed-app 으로 수정 부탁드립니다.

2023-08-08 01:19 UTC, imzeze commented on src/components/atoms/Pressable.tsx
Button용 Pressable을 말씀드린거여서.. 컴포넌트 이름을 Button으로 변경해주시기 바랍니다..!

2023-08-08 01:19 UTC, imzeze commented on src/components/atoms/Pressable.tsx
> +    <StyledPressable style={getComponentStyle()} onPress={onPress}>
음.. StyledComponent를 사용하도록 수정하는 것이 좋을 것 같습니다. 이 부분은 같이 수정해보는 게 좋을 것 같아요

2023-08-08 01:19 UTC, imzeze commented on src/components/atoms/Pressable.tsx
> +    <StyledPressable style={getComponentStyle()} onPress={onPress}>
이하 다른 컴포넌트도 동일합니다..!

2023-08-08 01:19 UTC, imzeze commented on src/components/pages/Home.tsx
> +                    onPress={() => navigation.navigate('Search')} >
expo router의 Link 참고 부탁드립니다..!

2023-08-08 23:26 UTC, beolggoolosori commented on app/_layout.tsx
> +import { createStackNavigator } from '@react-navigation/stack';
React-Native 문서 참고했습니다.

NavigationContainer: https://reactnavigation.org/docs/getting-started#wrapping-your-app-in-navigationcontainer

createStackNavigator: https://reactnavigation.org/docs/stack-navigator#api-definition

2023-08-14 05:34 UTC, imzeze approved these changes

2023-08-14 05:34 UTC, merged